version: "3.9"

services:
  frontend:
    build: 
      context: .
      target: build
    image: datatools-ui:latest
    volumes:
      - ./dist:/app/dist
      - ./lib:/app/lib
    ports:
      - "9966:9966"
      - "4000:4000"
